# Generated by Django 3.0.4 on 2020-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200612_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_cust_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
