# Generated by Django 3.0.4 on 2020-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menuitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
